apiVersion: v1
kind: Service
metadata:
  labels:
    app: fineract-frontend
  name: fineract-frontend
  namespace: pentaho-test  
spec:
  ports:
    - name: "9090"
      port: 9090
      targetPort: 80
  selector:
    app: fineract-frontend