apiVersion: v1
kind: Service
metadata:
  labels:
    app: fineract-server
  name: fineractmysql
  namespace: pentaho-test
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: fineract-server
    tier: fineractmysql
  #clusterIP: None