apiVersion: v1
kind: PersistentVolume
metadata:
  name: fineractmysql-pv-volume-pentaho
  namespace: pentaho-test  
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fineractmysql-pv-volume-pentaho
  namespace: pentaho-test  
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi