apiVersion: v1
kind: Service
metadata:
  labels:
    app: fineract-server
  name: fineract-server
  namespace: pentaho-test  
spec:
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 8443
  selector:
    app: fineract-server
    tier: backend
  type: LoadBalancer