apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fineract-server
  name: fineractmysql
  namespace: pentaho-test  
spec:
  selector:
    matchLabels:
      app: fineract-server
      tier: fineractmysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fineract-server
        tier: fineractmysql
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "5Gi"
              cpu: "2000m"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          livenessProbe:
            exec:
              command: ["sh","-c","mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD}"]
            failureThreshold: 10
            timeoutSeconds: 10
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - mysqladmin ping -uroot -p${MYSQL_PASSWORD}
            failureThreshold: 10
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
            - containerPort: 3306
              name: fineractmysql
          volumeMounts:
            - name: fineractmysql-initdb-pentaho
              mountPath: /docker-entrypoint-initdb.d/
            - name: fineractmysql-persistent-storage-pentaho
              mountPath: /var/lib/mysql/
      volumes:
        - name: fineractmysql-initdb-pentaho
          configMap:
            name: fineractmysql-initdb-pentaho
        - name: fineractmysql-persistent-storage-pentaho
          persistentVolumeClaim:
            claimName: fineractmysql-pv-volume-pentaho